array_layout="Block"
array_width=1
chain_indent="Block"
chain_one_line_max=4096
closure_block_indent_threshold=2
comment_width=120
condense_wildcard_suffices=true
control_brace_style="AlwaysNextLine"
disable_all_formatting=false
error_on_line_overflow=false
fn_args_density="Compressed"
fn_args_layout="Block"
fn_args_paren_newline=false
fn_brace_style="AlwaysNextLine"
fn_call_style="Block"
fn_call_width=4096
fn_empty_single_line=false
fn_return_indent="WithWhereClause"
fn_single_line=false
force_explicit_abi=true
force_format_strings=false
format_strings=false
generics_indent="Block"
hard_tabs=true
impl_empty_single_line=false
indent_match_arms=true
item_brace_style="AlwaysNextLine"
match_block_trailing_comma=true
max_width=4096
newline_style="Unix"
normalize_comments=true
reorder_imported_names=true
reorder_imports=true
single_line_if_else_max_width=4096
skip_children=false
space_after_bound_colon=true
space_after_type_annotation_colon=true
space_before_bound=false
space_before_type_annotation=false
spaces_around_ranges=true
spaces_within_angle_brackets=false
spaces_within_parens=false
spaces_within_square_brackets=false
struct_lit_multiline_style="ForceMulti"
struct_lit_style="Block"
struct_lit_width=1
struct_variant_width=1
tab_spaces=4
take_source_hints=true
trailing_comma="Vertical"
type_punctuation_density="Wide"
use_try_shorthand=true
where_density="Vertical"
where_layout="Vertical"
where_pred_indent="Block"
wrap_comments=false
wrap_match_arms=false
