# This file is part of .cargo. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/.cargo/master/COPYRIGHT. No part of .cargo, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright Â© 2016 The developers of .cargo. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/.cargo/master/COPYRIGHT.

verbose = false
skip_children = false
max_width = 4096
ideal_width = 4096
tab_spaces = 4
fn_call_width = 4096
struct_lit_width = 4096
newline_style = "Unix"
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
else_if_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
impl_empty_single_line = false
fn_empty_single_line = false
fn_single_line = false
fn_return_indent = "WithArgs"
fn_args_paren_newline = false
fn_args_density = "Tall"
fn_args_layout = "Visual"
fn_arg_indent = "Visual"
type_punctuation_density = "Wide"
where_density = "CompressedIfEmpty"
where_indent = "Tabbed"
where_layout = "Horizontal"
where_pred_indent = "Visual"
where_trailing_comma = true
generics_indent = "Visual"
struct_trailing_comma = "Always"
struct_lit_trailing_comma = "Always"
struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
enum_trailing_comma = true
report_todo = "Never"
report_fixme = "Never"
chain_base_indent = "Visual"
chain_indent = "Visual"
reorder_imports = true
single_line_if_else = false
format_strings = true
force_format_strings = false
chains_overflow_last = true
take_source_hints = true
hard_tabs = true
wrap_comments = false
normalise_comments = true
wrap_match_arms = false
match_block_trailing_comma = true
match_wildcard_trailing_comma = true
write_mode = "Overwrite"
